#!/bin/sh
#
# A hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.

# Redirect output to stderr.
exec 1>&2

for f in .githooks/pre-commit.*; do
  n=$(echo "${f}" |sed 's/^.*pre-commit\.//')
  echo "running ${n} pre-commit"
  $(${f})
done
