language: bash

env:
  - SHUNIT_COLOR='always'

script:
  # Execute the unit tests.
  - ./test_runner

addons:
  apt:
    packages:
      - ksh
      - zsh

matrix:
  include:
    - os: linux
      # Ubuntu Bionic 18.04
      dist: bionic
    - os: linux
      # Ubuntu Xenial 16.04
      dist: xenial
    - os: osx
    - os: linux
      script:
        # Run the source through ShellCheck (http://www.shellcheck.net).
        - shellcheck *_test.sh
        - shellcheck -s sh shflags shflags_test_helpers

branches:
  only:
  - master
  - 1.0.x
  # Tags, e.g. v.1.2.3.
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
